POST http://localhost:8000/subscribers/many
Content-Type: application/json

[
    {
        "name": "Hardwell",
        "best_mv_name": "Spaceman",
        "genre": "BigRoom, TechRoom",
        "youtube_subscriber": "5.08M",
        "spotify_id": "6BrvowZBreEkXzJQMpL174",
        "spotify_followers": "3687207",
        "spotify_stream_count": "6,473,051"
    },
    {
        "name": "Don Diablo",
        "best_mv_name": "Cutting Shapes",
        "genre": "Future House",
        "youtube_subscriber": "1.35M",
        "spotify_id": "1l2ekx5skC4gJH8djERwh1",
        "spotify_followers": "1810900",
        "spotify_stream_count": "6,713,338"
    },
    {
        "name": "Martin Garrix",
        "best_mv_name": "Animals",
        "genre": "Future House, BigRoom",
        "youtube_subscriber": "14.5M", 
        "spotify_followers": "15758978",
        "spotify_id": "60d24wfXkVzDSfLS6hyCjZ",
        "spotify_stream_count": "23,205,390"
    },
    {
        "name": "Sub Zero Project",
        "best_mv_name": "Darkest Hour",
        "genre": "Hardstyle, Euphoric Hardstyle",
        "youtube_subscriber": "74,580",
        "spotify_followers": "160613",
        "spotify_id": "4f0OXMMSxr0r8Ztx6CdpAl",
        "spotify_stream_count": "1,765,107"
    },
    {
        "name": "Apashe",
        "best_mv_name": "Majesty",
        "genre": "Trap, Dubstep",
        "youtube_subscriber": "315K",
        "spotify_id": "1fd3fmwlhrDl2U5wbbPQYN",
        "spotify_followers": "293141",
        "spotify_stream_count": "2,085,245"
    },
    {
        "name": "Coone",
        "best_mv_name": "Toss A Coin To Your Witcher",
        "genre": "Trap, Dubstep",
        "youtube_subscriber": "254K",
        "spotify_id": "1Wt63OMKtv6v2ivHuQLm2C",
        "spotify_followers": "181266",
        "spotify_stream_count": "1,669,295"
    },
    {
        "name": "Dimitri Vegas & Like Mike",
        "best_mv_name": "Tremor",
        "genre": "BigRoom, Electro House",
        "youtube_subscriber": "5.22M",
        "spotify_id": "73jBynjsVtofjRpdpRAJGk",
        "spotify_followers": "3333107",
        "spotify_stream_count": "10,596,184"
    },
    {
        "name": "Avicii",
        "best_mv_name": "Wake Me Up",
        "genre": "Progressive House",
        "youtube_subscriber": "20.5M",
        "spotify_id": "1vCWHaC5f2uS3yhpwWbIA6",
        "spotify_followers": "22689592",
        "spotify_stream_count": "34,357,452"
    },
    {
        "name": "KSHMR",
        "best_mv_name": "Secrets",
        "genre": "BigRoom, Indian BigRoom",
        "youtube_subscriber": "1.75M",
        "spotify_id": "2wX6xSig4Rig5kZU6ePlWe",
        "spotify_followers": "1709458",
        "spotify_stream_count": "5,611,944"
    },
    {
        "name": "W&W",
        "best_mv_name": "Bigfoot",
        "genre": "BigRoom, Electro House",
        "youtube_subscriber": "1.07M",
        "spotify_id": "2rTo8KIkBTFjQS7VvaKYQ4",
        "spotify_followers": "807136",
        "spotify_stream_count": "5,660,946"
    },
    {
        "name": "Crunkz",
        "best_mv_name": "Superlike",
        "genre": "Future House, Electro House",
        "youtube_subscriber": "580K",
        "spotify_id": "4OXIfQQfNxUxqVPwoklWcv",
        "spotify_followers": "53775",
        "spotify_stream_count": "1,092,564"
    }
]